name: Launch EC2 Instance

on:
  workflow_dispatch: 

env:
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  launch_ec2:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up AWS credentials from GitHub Secrets
      run: |
        echo "aws_access_key_id=${{ secrets.TF_USER_AWS_KEY }}" >> $GITHUB_ENV
        echo "aws_secret_access_key=${{ secrets.TF_USER_AWS_SECRET }}" >> $GITHUB_ENV

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform configuration
      id: plan
      run: terraform plan -out=tfplan

    - name: Apply Terraform configuration
      run: terraform apply tfplan -var "branch_name=${{ env.BRANCH_NAME }}"
        
    # - name: Configure AWS CLI
    #   run: |
    #     aws configure set region "us-east-2"  # Replace with your desired region

    # - name: Run Terraform init
    #   working-directory:  "./.github/workflows"
    #   env:
    #     TF_VAR_aws_access_key_id: ${{ secrets.TF_USER_AWS_KEY }}
    #     TF_VAR_aws_secret_access_key: ${{ secrets.TF_USER_AWS_SECRET }}
    #     TF_VAR_region: "us-east-2"  # Replace with your desired region
    #   run: |
    #     terraform init
        
    # - name: Apply Terraform configuration
    #   working-directory:  "./.github/workflows"
    #   env:
    #     TF_VAR_aws_access_key_id: ${{ secrets.TF_USER_AWS_KEY }}
    #     TF_VAR_aws_secret_access_key: ${{ secrets.TF_USER_AWS_SECRET }}
    #     TF_VAR_region: "us-east-2"  # Replace with your desired region
    #   run: |
    #     terraform fmt
    #     terraform validate  
    #     terraform apply -auto-approve 
        
    # - name: Log Terraform output
    #   working-directory:  "./.github/workflows"
    #   env:
    #     TF_VAR_aws_access_key_id: ${{ secrets.TF_USER_AWS_KEY }}
    #     TF_VAR_aws_secret_access_key: ${{ secrets.TF_USER_AWS_SECRET }}
    #     TF_VAR_region: "us-east-2"  # Replace with your desired region
    #   run: |
    #     terraform show -json
        
    # - name: Clean up Terraform state
    #   working-directory:  "./.github/workflows"
    #   env:
    #     TF_VAR_aws_access_key_id: ${{ secrets.TF_USER_AWS_KEY }}
    #     TF_VAR_aws_secret_access_key: ${{ secrets.TF_USER_AWS_SECRET }}
    #     TF_VAR_region: "us-east-2"  # Replace with your desired region
    #   run: |
    #     terraform destroy -auto-approve