name: Launch EC2 Instance

on:
  workflow_dispatch: 

jobs:
  launch_ec2:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up AWS credentials from GitHub Secrets
      run: |
        echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

    - name: Install required tools
      run: |
        apt-get update
        apt-get install -y unzip gnupg software-properties-common gpg wget

    - name: Configure AWS CLI
      run: |
        aws configure set region "us-east-2"  # Replace with your desired region

    - name: Run Terraform init
      env:
        TF_VAR_aws_access_key_id: ${{ env.aws_access_key_id }}
        TF_VAR_aws_secret_access_key: ${{ env.aws_secret_access_key }}
        TF_VAR_region: "us-east-2"  # Replace with your desired region
      run: |
        cat /etc/os-release
        terraform init
        
    - name: Apply Terraform configuration
      env:
        TF_VAR_aws_access_key_id: ${{ env.aws_access_key_id }}
        TF_VAR_aws_secret_access_key: ${{ env.aws_secret_access_key }}
        TF_VAR_region: "us-east-2"  # Replace with your desired region
      run: |
        terraform apply -auto-approve
        
    - name: Log Terraform output
      env:
        TF_VAR_aws_access_key_id: ${{ env.aws_access_key_id }}
        TF_VAR_aws_secret_access_key: ${{ env.aws_secret_access_key }}
        TF_VAR_region: "us-east-2"  # Replace with your desired region
      run: |
        terraform show -json
        
    - name: Clean up Terraform state
      env:
        TF_VAR_aws_access_key_id: ${{ env.aws_access_key_id }}
        TF_VAR_aws_secret_access_key: ${{ env.aws_secret_access_key }}
        TF_VAR_region: "us-east-2"  # Replace with your desired region
      run: |
        terraform destroy -auto-approve